### ISSUE TITLE
Certain Properties Not Shown

### ISSUE THREAD

**Issue by benben3963** [ClockworkSquirrel/roblox-dump-parser#1]
When using **GetPropertyList** some of the properties on the object's Class are not sent. For **Part** I noticed **Anchored**, **Name**, and **BackParamA** are missing.

**Comment by ClockworkSquirrel** [comment]
I will investigate this later. Thanks for bringing it up.

**Comment by ClockworkSquirrel** [comment]
The issue should now be fixed. Thanks for the feedback.
